// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class BloodPressure
{
    public int BloodPressureId { get; set; }

    public int? ElderlyId { get; set; }

    public DateTime? DateRecorded { get; set; }

    public int? Systolic { get; set; }

    public int? Diastolic { get; set; }

    public string SystolicSource { get; set; }

    public string DiastolicSource { get; set; }

    public string Status { get; set; }

    public virtual Elderly Elderly { get; set; }
}