// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class BloodGlucose
{
    public int BloodGlucoseId { get; set; }

    public int? ElderlyId { get; set; }

    public DateTime? DateRecorded { get; set; }

    public decimal? BloodGlucose1 { get; set; }

    public string BloodGlucoseSource { get; set; }

    public string Status { get; set; }
}