// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Book
{
    public int BookId { get; set; }

    public int? AccountId { get; set; }

    public string BookName { get; set; }

    public string BookUrl { get; set; }

    public string BookType { get; set; }

    public string Author { get; set; }

    public DateTime? PublishDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string Status { get; set; }

    public virtual Account Account { get; set; }
}