// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int FamilyMemberId { get; set; }

    public int ElderlyId { get; set; }

    public int? ComboId { get; set; }

    public string Type { get; set; }

    public decimal Price { get; set; }

    public DateTime BookingDate { get; set; }

    public string PaymentMethod { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public virtual Combo Combo { get; set; }

    public virtual Elderly Elderly { get; set; }

    public virtual FamilyMember FamilyMember { get; set; }

    public virtual ICollection<ProfessorAppointment> ProfessorAppointments { get; set; } = new List<ProfessorAppointment>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual ICollection<UserService> UserServices { get; set; } = new List<UserService>();
}