// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int AccountId { get; set; }

    public int ElderlyId { get; set; }

    public int? SubscriptionId { get; set; }

    public string Type { get; set; }

    public decimal Price { get; set; }

    public DateTime BookingDate { get; set; }

    public string PaymentMethod { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public int? TransactionId { get; set; }

    public virtual FamilyMember Account { get; set; }

    public virtual Elderly Elderly { get; set; }

    public virtual ICollection<ProfessorAppointment> ProfessorAppointments { get; set; } = new List<ProfessorAppointment>();

    public virtual Subscription Subscription { get; set; }

    public virtual Transaction Transaction { get; set; }

    public virtual Transaction TransactionNavigation { get; set; }

    public virtual ICollection<UserSubscription> UserSubscriptions { get; set; } = new List<UserSubscription>();
}