// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Elderly
{
    public int ElderlyId { get; set; }

    public int AccountId { get; set; }

    public string Allergy { get; set; }

    public string LivingSituation { get; set; }

    public string MedicalRecord { get; set; }

    public decimal Weight { get; set; }

    public decimal Height { get; set; }

    public string Status { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();

    public virtual ICollection<BloodGlucose> BloodGlucoses { get; set; } = new List<BloodGlucose>();

    public virtual ICollection<BloodPressure> BloodPressures { get; set; } = new List<BloodPressure>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<EmergencyConfirmation> EmergencyConfirmations { get; set; } = new List<EmergencyConfirmation>();

    public virtual ICollection<HeartRate> HeartRates { get; set; } = new List<HeartRate>();

    public virtual ICollection<Height> Heights { get; set; } = new List<Height>();

    public virtual ICollection<Iotdevice> Iotdevices { get; set; } = new List<Iotdevice>();

    public virtual ICollection<KidneyFunction> KidneyFunctions { get; set; } = new List<KidneyFunction>();

    public virtual ICollection<LipidProfile> LipidProfiles { get; set; } = new List<LipidProfile>();

    public virtual ICollection<LiverEnzyme> LiverEnzymes { get; set; } = new List<LiverEnzyme>();

    public virtual ICollection<Medication> Medications { get; set; } = new List<Medication>();

    public virtual ICollection<Prescription> Prescriptions { get; set; } = new List<Prescription>();

    public virtual ICollection<ProfessorAppointment> ProfessorAppointments { get; set; } = new List<ProfessorAppointment>();

    public virtual ICollection<ProfessorRating> ProfessorRatings { get; set; } = new List<ProfessorRating>();

    public virtual ICollection<Weight> Weights { get; set; } = new List<Weight>();
}