// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class EmergencyConfirmation
{
    public int EmergencyConfirmationId { get; set; }

    public int? ElderlyId { get; set; }

    public int? ConfirmationAccountId { get; set; }

    public DateTime? ConfirmationDate { get; set; }

    public bool? IsConfirm { get; set; }

    public DateTime? EmergencyDate { get; set; }

    public string Status { get; set; }

    public virtual Account ConfirmationAccount { get; set; }

    public virtual Elderly Elderly { get; set; }

    public virtual ICollection<EmergencyInformation> EmergencyInformations { get; set; } = new List<EmergencyInformation>();
}