// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class EmergencyConfirmation
{
    public int EmergencyConfirmationId { get; set; }

    public int? FamilyMemberId { get; set; }

    public int? ElderlyId { get; set; }

    public DateTime? DateTime { get; set; }

    public string Status { get; set; }

    public virtual Elderly Elderly { get; set; }

    public virtual FamilyMember FamilyMember { get; set; }
}