// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class EmergencyInformation
{
    public int EmergencyInformationId { get; set; }

    public int? EmergencyConfirmationId { get; set; }

    public string FrontCameraImage { get; set; }

    public string RearCameraImage { get; set; }

    public string Longitude { get; set; }

    public string Latitude { get; set; }

    public DateTime? DateTime { get; set; }

    public string Status { get; set; }

    public virtual EmergencyConfirmation EmergencyConfirmation { get; set; }
}