// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class FootStep
{
    public int FootStepId { get; set; }

    public int? ElderlyId { get; set; }

    public decimal? FootStep1 { get; set; }

    public DateTime? DateRecorded { get; set; }

    public string CreatedBy { get; set; }

    public string Status { get; set; }

    public virtual Elderly Elderly { get; set; }
}