// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class HealthIndicatorBase
{
    public int Id { get; set; }

    public string Type { get; set; }

    public decimal MinValue { get; set; }

    public decimal MaxValue { get; set; }

    public DateTime Time { get; set; }

    public string Status { get; set; }

    public int? AccountId { get; set; }

    public virtual Account Account { get; set; }
}