// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class HealthIndicatorsBase
{
    public int HealthIndicatorsBaseId { get; set; }

    public int? SystolicMax { get; set; }

    public int? SystolicMin { get; set; }

    public int? DiastolicMax { get; set; }

    public int? DiastolicMin { get; set; }

    public decimal? Bunmax { get; set; }

    public decimal? Bunmin { get; set; }

    public decimal? EGfrmax { get; set; }

    public decimal? EGfrmin { get; set; }

    public decimal? TotalCholesterolMax { get; set; }

    public decimal? TotalCholesterolMin { get; set; }

    public decimal? LdlcholesterolMax { get; set; }

    public decimal? LdlcholesterolMin { get; set; }

    public decimal? HdlcholesterolMax { get; set; }

    public decimal? HdlcholesterolMin { get; set; }

    public decimal? TriglyceridesMax { get; set; }

    public decimal? TriglyceridesMin { get; set; }

    public decimal? Altmax { get; set; }

    public decimal? Altmin { get; set; }

    public decimal? Astmax { get; set; }

    public decimal? Astmin { get; set; }

    public decimal? Alpmax { get; set; }

    public decimal? Alpmin { get; set; }

    public decimal? Ggtmax { get; set; }

    public decimal? Ggtmin { get; set; }

    public int? AverageOfHeartRateMax { get; set; }

    public int? AverageOfHeartRateMin { get; set; }

    public decimal? BloodGlucoseMax { get; set; }

    public decimal? BloodGlucoseMin { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Status { get; set; }
}