// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class HealthIndicator
{
    public int HealthIndicatorId { get; set; }

    public int ElderlyId { get; set; }

    public DateTime DateRecorded { get; set; }

    public decimal? BloodPressureSystolic { get; set; }

    public string BloodPressureSystolicSource { get; set; }

    public decimal? BloodPressureDiastolic { get; set; }

    public string BloodPressureDiastolicSource { get; set; }

    public int? HeartRate { get; set; }

    public string HeartRateSource { get; set; }

    public decimal? Weight { get; set; }

    public string WeightSource { get; set; }

    public decimal? Height { get; set; }

    public string HeightSource { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public decimal? BloodGlucose { get; set; }

    public string BloodGlucoseSource { get; set; }

    public decimal? TotalCholesterol { get; set; }

    public decimal? Ldlcholesterol { get; set; }

    public decimal? Hdlcholesterol { get; set; }

    public decimal? Triglycerides { get; set; }

    public string LipidProfileSource { get; set; }

    public decimal? Alt { get; set; }

    public decimal? Ast { get; set; }

    public decimal? Alp { get; set; }

    public decimal? Ggt { get; set; }

    public string LiverEnzymesSource { get; set; }

    public decimal? Creatinine { get; set; }

    public decimal? Bun { get; set; }

    public decimal? EGfr { get; set; }

    public string KidneyFunctionSource { get; set; }

    public virtual Elderly Elderly { get; set; }
}