// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class KidneyFunction
{
    public int KidneyFunctionId { get; set; }

    public int? ElderlyId { get; set; }

    public DateTime? DateRecorded { get; set; }

    public decimal? Creatinine { get; set; }

    public decimal? Bun { get; set; }

    public decimal? EGfr { get; set; }

    public string KidneyFunctionSource { get; set; }

    public string Status { get; set; }
}