// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Lesson
{
    public int LessonId { get; set; }

    public int ContentProviderId { get; set; }

    public string LessonName { get; set; }

    public string LessonDescription { get; set; }

    public string Status { get; set; }

    public virtual ContentProvider ContentProvider { get; set; }

    public virtual ICollection<LessonFeedback> LessonFeedbacks { get; set; } = new List<LessonFeedback>();

    public virtual ICollection<LessonHistory> LessonHistories { get; set; } = new List<LessonHistory>();
}