// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class LipidProfile
{
    public int LipidProfileId { get; set; }

    public int? ElderlyId { get; set; }

    public DateTime? DateRecorded { get; set; }

    public decimal? TotalCholesterol { get; set; }

    public decimal? Ldlcholesterol { get; set; }

    public decimal? Hdlcholesterol { get; set; }

    public decimal? Triglycerides { get; set; }

    public string LipidProfileSource { get; set; }

    public string Status { get; set; }

    public string CreatedBy { get; set; }

    public virtual Elderly Elderly { get; set; }
}