// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class LiverEnzyme
{
    public int LiverEnzymesId { get; set; }

    public int? ElderlyId { get; set; }

    public DateTime? DateRecorded { get; set; }

    public decimal? Alt { get; set; }

    public decimal? Ast { get; set; }

    public decimal? Alp { get; set; }

    public decimal? Ggt { get; set; }

    public string LiverEnzymesSource { get; set; }

    public string Status { get; set; }

    public string CreatedBy { get; set; }

    public virtual Elderly Elderly { get; set; }
}