// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Medication
{
    public int MedicationId { get; set; }

    public int ElderlyId { get; set; }

    public string MedicationName { get; set; }

    public string Treatment { get; set; }

    public string Shape { get; set; }

    public string Dosage { get; set; }

    public bool? IsBeforeMeal { get; set; }

    public string FrequencyType { get; set; }

    public string TimeFrequency { get; set; }

    public int? DateFrequency { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public DateTime CreatedDate { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public int PrescriptionId { get; set; }

    public int? Remaining { get; set; }

    public virtual Elderly Elderly { get; set; }

    public virtual ICollection<MedicationSchedule> MedicationSchedules { get; set; } = new List<MedicationSchedule>();

    public virtual Prescription Prescription { get; set; }
}