// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Music
{
    public int MusicId { get; set; }

    public int? PlaylistId { get; set; }

    public int? AccountId { get; set; }

    public string MusicName { get; set; }

    public string MusicUrl { get; set; }

    public string Singer { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string Status { get; set; }

    public virtual Account Account { get; set; }

    public virtual Playlist Playlist { get; set; }
}