// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Playlist
{
    public int PlaylistId { get; set; }

    public int? AccountId { get; set; }

    public string PlaylistName { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string Status { get; set; }

    public string ImageUrl { get; set; }

    public bool? IsLesson { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();

    public virtual ICollection<Music> Musics { get; set; } = new List<Music>();
}