// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Prescription
{
    public int PrescriptionId { get; set; }

    public int Elderly { get; set; }

    public string Url { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Status { get; set; }

    public string Name { get; set; }

    public virtual Elderly ElderlyNavigation { get; set; }

    public virtual ICollection<Medication> Medications { get; set; } = new List<Medication>();
}