// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class ProfessorAppointment
{
    public int ProfessorAppointmentId { get; set; }

    public int ElderlyId { get; set; }

    public int? UserSubscriptionId { get; set; }

    public DateTime AppointmentTime { get; set; }

    public string Description { get; set; }

    public DateTime CreatedDate { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public string Status { get; set; }

    public string Content { get; set; }

    public string Solution { get; set; }

    public bool? IsOnline { get; set; }

    public virtual Elderly Elderly { get; set; }

    public virtual ProfessorRating ProfessorRating { get; set; }

    public virtual UserSubscription UserSubscription { get; set; }
}