// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class ProfessorReport
{
    public int ProfessorReportId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string Status { get; set; }
}