// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Subscription
{
    public int SubscriptionId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal Fee { get; set; }

    public DateTime ValidityPeriod { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime UpdatedDate { get; set; }

    public string Status { get; set; }

    public int? AccountId { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}