// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class SystemReport
{
    public int ReportId { get; set; }

    public int? AccountId { get; set; }

    public string ReportTitle { get; set; }

    public string ReportContent { get; set; }

    public string AttachmentUrl { get; set; }

    public string ReportType { get; set; }

    public string PriorityLevel { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Account Account { get; set; }
}