// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public int AccountId { get; set; }

    public int? BookingId { get; set; }

    public decimal Price { get; set; }

    public string PaymentLink { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime PaymentDate { get; set; }

    public string PaymentCode { get; set; }

    public virtual Account Account { get; set; }

    public virtual Booking Booking { get; set; }
}