// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Weight
{
    public int WeightId { get; set; }

    public int? ElderlyId { get; set; }

    public DateTime? DateRecorded { get; set; }

    public decimal? Weight1 { get; set; }

    public string WeightSource { get; set; }

    public string Status { get; set; }

    public virtual Elderly Elderly { get; set; }
}