// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class WeightHeight
{
    public int WeightHeightId { get; set; }

    public int? ElderlyId { get; set; }

    public DateTime? DateRecorded { get; set; }

    public decimal? Weight { get; set; }

    public string WeightSource { get; set; }

    public decimal? Height { get; set; }

    public string HeightSource { get; set; }

    public string Status { get; set; }
}